const functions = require('firebase-functions');
const admin = require('firebase-admin');

admin.initializeApp();

// // Create and Deploy Your First Cloud Functions
// // https://firebase.google.com/docs/functions/write-firebase-functions
//
// exports.helloWorld = functions.https.onRequest((request, response) => {
//  response.send("Hello from Firebase!");
// });

exports.signup = functions.https.onRequest(async (req, res) => {
  /*
  TODO: Input validation before creating a new user. This should be 
  done on the client side anyways, but also here on the server just in case.
  */ 

  // very basic for now, needs a lot more error handling.
  const {email, password, name} = req.body;
  try {
    const user = await admin.auth().createUser({
      email: email,
      password: password,
      displayName: displayName,
      emailVerified: false,
      disabled: false
    })

    /* Store user details in a Users collection here*/

    /* Now generate a custom JWT to send back to the client */
    const uid = '' //uid is the newly created users unique id, generated by createUser()
    const token = await admin.auth().createCustomToken(uid);
    res.status(201).send({jwt: token});
    
  } catch (error) {
    // need to remove this error message in production.
    res.status(500).send(error);
  }
});

exports.signin = functions.https.onRequest(async(req, res)=>{
  
});