export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

export const GET_PUBLICUSERPROFILE_START = 'GET_PUBLICUSERPROFILE_START';
export const GET_PUBLICUSERPROFILE_SUCCESS = 'GET_PUBLICUSERPROFILE_SUCCESS';
export const GET_PUBLICUSERPROFILE_FAIL = 'GET_PUBLICUSERPROFILE_FAIL';

export const POST_BIOGRAPHY_START = 'POST_BIOGRAPHY_START';
export const POST_BIOGRAPHY_FAIL = 'POST_BIOGRAPHY_FAIL';
export const POST_BIOGRAPHY_SUCCESS = 'POST_BIOGRAPHY_SUCCESS';

export const POST_SUBJECTEXPERIENCE_START = 'POST_SUBJECTEXPERIENCE_START';
export const POST_SUBJECTEXPERIENCE_FAIL = 'POST_SUBJECTEXPERIENCE_FAIL';
export const POST_SUBJECTEXPERIENCE_SUCCESS = 'POST_SUBJECTEXPERIENCE_SUCCESS';

export const POST_SUBJECTTAGS_START = 'POST_SUBJECTTAGS_START';
export const POST_SUBJECTTAGS_FAIL = 'POST_SUBJECTTAGS_FAIL';
export const POST_SUBJECTTAGS_SUCCESS = 'POST_SUBJECTTAGS_SUCCESS';

export const POST_PROJECTPOSITIONS_START = 'POST_PROJECTPOSITIONS_START';
export const POST_PROJECTPOSITIONS_FAIL = 'POST_PROJECTPOSITIONS_FAIL';
export const POST_PROJECTPOSITIONS_SUCCESS = 'POST_PROJECTPOSITIONS_SUCCESS';